#' SolarEnergyPrediction
#'
#' The PV generation forecast for unmetered PV systems makes it possible to predict production of a PV system on an hourly basis for the next 4 days without having your own metering equipment or system-specific generation data.
#'
#' The version of the OpenAPI document: 1.0.0
#' Contact: dev@stromdao.com
#' Generated by: https://openapi-generator.tech
#'

#' @docType class
#' @title Default operations
#' @description openapi.Default
#' @format An \code{R6Class} generator object
#' @field api_client Handles the client-server communication.
#'
#' @section Methods:
#' \describe{
#' \strong{ Prediction } \emph{ Retrieve PV Forecast without metering }
#' The PV generation forecast for unmetered PV systems makes it possible to predict production of a PV system on an hourly basis for the next 4 days without having your own metering equipment or system-specific generation data.
#'
#' \itemize{
#' \item \emph{ @param } x_rapid_api_key character
#' \item \emph{ @param } x_rapid_api_host Enum < [solarenergyprediction.p.rapidapi.com] >
#' \item \emph{ @param } lat numeric
#' \item \emph{ @param } lon numeric
#' \item \emph{ @param } zip character
#' \item \emph{ @param } deg integer
#' \item \emph{ @param } az integer
#' \item \emph{ @param } wp integer
#' \item \emph{ @param } loss integer
#' \item \emph{ @param } plant character
#' \item \emph{ @param } decoration Enum < [forecast.solar] >
#'
#'
#' \item status code : 200 | SolarEnergy Prediction for the upcoming 4 days.  
#'
#'
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' }
#'
#'
#' @examples
#' \dontrun{
#' ####################  Prediction  ####################
#'
#' library(openapi)
#' var.x_rapid_api_key <- 'x_rapid_api_key_example' # character | API Key from rapidapi.com
#' var.x_rapid_api_host <- 'x_rapid_api_host_example' # character | API Host to use (should be `solarenergyprediction.p.rapidapi.com` )
#' var.lat <- 49.3418836 # numeric | Geocode latitude of pv plant (required if parameter plant or zip is not given).
#' var.lon <- 8.8006813 # numeric | Geocode longitude of pv plant (required if parameter plant or zip is not given).
#' var.zip <- '69256' # character | Zipcode (postalcode) - works only for Germany. If specified no lat/lon parameter is required.
#' var.deg <- 35 # integer | plane declination degrees, 0 (horizontal) … 90 (vertical)
#' var.az <- 0 # integer | plant installation azimuth, -180 … 180 (-180 = north, -90 = east, 0 = south, 90 = west, 180 = north)
#' var.wp <- 6000 # integer | Installed Watt-Peak  (eq. kWp/1000)
#' var.loss <- 14 # integer | System loss in percent (defaults to 14)
#' var.plant <- 'plant_example' # character | If specified all other query parameters will be taken from the stored value and must not be given with the query string.    Use as comma separated list of IDs to retrieve a forecast for multiple specifications.
#' var.decoration <- 'decoration_example' # character | Allows to use SolarPredictionAPI as a plug-in replacement for other APIs.    Supported decorations:    | `forecast.solar` | Output will be formated like [https://forecast.solar](http://doc.forecast.solar/doku.php?id=api:estimate#example) |  |----|----|
#'
#' #Retrieve PV Forecast without metering
#' api.instance <- DefaultApi$new()
#'
#' result <- api.instance$Prediction(var.x_rapid_api_key, var.x_rapid_api_host, lat=var.lat, lon=var.lon, zip=var.zip, deg=var.deg, az=var.az, wp=var.wp, loss=var.loss, plant=var.plant, decoration=var.decoration)
#'
#'
#' }
#' @importFrom R6 R6Class
#' @importFrom base64enc base64encode
#' @export
DefaultApi <- R6::R6Class(
  "DefaultApi",
  public = list(
    api_client = NULL,
    #' Initialize a new DefaultApi.
    #'
    #' @description
    #' Initialize a new DefaultApi.
    #'
    #' @param api_client An instance of API client.
    #' @export
    initialize = function(api_client) {
      if (!missing(api_client)) {
        self$api_client <- api_client
      }
      else {
        self$api_client <- ApiClient$new()
      }
    },
    #' Retrieve PV Forecast without metering
    #'
    #' @description
    #' Retrieve PV Forecast without metering
    #'
    #' @param x_rapid_api_key API Key from rapidapi.com
    #' @param x_rapid_api_host API Host to use (should be `solarenergyprediction.p.rapidapi.com` )
    #' @param lat (optional) Geocode latitude of pv plant (required if parameter plant or zip is not given).
    #' @param lon (optional) Geocode longitude of pv plant (required if parameter plant or zip is not given).
    #' @param zip (optional) Zipcode (postalcode) - works only for Germany. If specified no lat/lon parameter is required.
    #' @param deg (optional) plane declination degrees, 0 (horizontal) … 90 (vertical)
    #' @param az (optional) plant installation azimuth, -180 … 180 (-180 = north, -90 = east, 0 = south, 90 = west, 180 = north)
    #' @param wp (optional) Installed Watt-Peak  (eq. kWp/1000)
    #' @param loss (optional) System loss in percent (defaults to 14)
    #' @param plant (optional) If specified all other query parameters will be taken from the stored value and must not be given with the query string.    Use as comma separated list of IDs to retrieve a forecast for multiple specifications.
    #' @param decoration (optional) Allows to use SolarPredictionAPI as a plug-in replacement for other APIs.    Supported decorations:    | `forecast.solar` | Output will be formated like [https://forecast.solar](http://doc.forecast.solar/doku.php?id=api:estimate#example) |  |----|----|
    #' @param ... Other optional arguments
    #' @return void
    #' @export
    Prediction = function(x_rapid_api_key, x_rapid_api_host, lat=NULL, lon=NULL, zip=NULL, deg=NULL, az=NULL, wp=NULL, loss=NULL, plant=NULL, decoration=NULL, ...) {
      api_response <- self$PredictionWithHttpInfo(x_rapid_api_key, x_rapid_api_host, lat, lon, zip, deg, az, wp, loss, plant, decoration, ...)
      resp <- api_response$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        api_response$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        api_response
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        api_response
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        api_response
      }
    },
    #' Retrieve PV Forecast without metering
    #'
    #' @description
    #' Retrieve PV Forecast without metering
    #'
    #' @param x_rapid_api_key API Key from rapidapi.com
    #' @param x_rapid_api_host API Host to use (should be `solarenergyprediction.p.rapidapi.com` )
    #' @param lat (optional) Geocode latitude of pv plant (required if parameter plant or zip is not given).
    #' @param lon (optional) Geocode longitude of pv plant (required if parameter plant or zip is not given).
    #' @param zip (optional) Zipcode (postalcode) - works only for Germany. If specified no lat/lon parameter is required.
    #' @param deg (optional) plane declination degrees, 0 (horizontal) … 90 (vertical)
    #' @param az (optional) plant installation azimuth, -180 … 180 (-180 = north, -90 = east, 0 = south, 90 = west, 180 = north)
    #' @param wp (optional) Installed Watt-Peak  (eq. kWp/1000)
    #' @param loss (optional) System loss in percent (defaults to 14)
    #' @param plant (optional) If specified all other query parameters will be taken from the stored value and must not be given with the query string.    Use as comma separated list of IDs to retrieve a forecast for multiple specifications.
    #' @param decoration (optional) Allows to use SolarPredictionAPI as a plug-in replacement for other APIs.    Supported decorations:    | `forecast.solar` | Output will be formated like [https://forecast.solar](http://doc.forecast.solar/doku.php?id=api:estimate#example) |  |----|----|
    #' @param ... Other optional arguments
    #' @return API response (void) with additional information such as HTTP status code, headers
    #' @export
    PredictionWithHttpInfo = function(x_rapid_api_key, x_rapid_api_host, lat=NULL, lon=NULL, zip=NULL, deg=NULL, az=NULL, wp=NULL, loss=NULL, plant=NULL, decoration=NULL, ...) {
      args <- list(...)
      query_params <- list()
      header_params <- c()

      if (missing(`x_rapid_api_key`)) {
        stop("Missing required parameter `x_rapid_api_key`.")
      }

      if (missing(`x_rapid_api_host`)) {
        stop("Missing required parameter `x_rapid_api_host`.")
      }

      body <- NULL
      url_path <- "/v2.0/solar/prediction"

      resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, url_path),
                                 method = "GET",
                                 query_params = query_params,
                                 header_params = header_params,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        ApiResponse$new(NULL, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned ", httr::status_code(resp), " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    }
  )
)
