# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test DefaultApi")

api_instance <- DefaultApi$new()

test_that("Prediction", {
  # tests for Prediction
  # base path: https://solarenergyprediction.p.rapidapi.com
  # Retrieve PV Forecast without metering
  # The PV generation forecast for unmetered PV systems makes it possible to predict production of a PV system on an hourly basis for the next 4 days without having your own metering equipment or system-specific generation data.
  # @param x_rapid_api_key character API Key from rapidapi.com
  # @param x_rapid_api_host character API Host to use (should be `solarenergyprediction.p.rapidapi.com` )
  # @param lat numeric Geocode latitude of pv plant (required if parameter plant or zip is not given). (optional)
  # @param lon numeric Geocode longitude of pv plant (required if parameter plant or zip is not given). (optional)
  # @param zip character Zipcode (postalcode) - works only for Germany. If specified no lat/lon parameter is required. (optional)
  # @param deg integer plane declination degrees, 0 (horizontal) … 90 (vertical) (optional)
  # @param az integer plant installation azimuth, -180 … 180 (-180 = north, -90 = east, 0 = south, 90 = west, 180 = north) (optional)
  # @param wp integer Installed Watt-Peak  (eq. kWp/1000) (optional)
  # @param loss integer System loss in percent (defaults to 14) (optional)
  # @param plant character If specified all other query parameters will be taken from the stored value and must not be given with the query string.    Use as comma separated list of IDs to retrieve a forecast for multiple specifications. (optional)
  # @param decoration character Allows to use SolarPredictionAPI as a plug-in replacement for other APIs.    Supported decorations:    | `forecast.solar` | Output will be formated like [https://forecast.solar](http://doc.forecast.solar/doku.php?id=api:estimate#example) |  |----|----| (optional)
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
