#
# SolarEnergyPrediction
# The PV generation forecast for unmetered PV systems makes it possible to predict production of a PV system on an hourly basis for the next 4 days without having your own metering equipment or system-specific generation data.
# Version: 1.0.0
# Contact: dev@stromdao.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'DefaultApi' {
    Context 'Invoke-Prediction' {
        It 'Test Invoke-Prediction' {
            #$TestResult = Invoke-Prediction -XRapidAPIKey "TEST_VALUE" -XRapidAPIHost "TEST_VALUE" -Lat "TEST_VALUE" -Lon "TEST_VALUE" -Zip "TEST_VALUE" -Deg "TEST_VALUE" -Az "TEST_VALUE" -Wp "TEST_VALUE" -Loss "TEST_VALUE" -Plant "TEST_VALUE" -Decoration "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

}
