"""
    SolarEnergyPrediction

    The PV generation forecast for unmetered PV systems makes it possible to predict production of a PV system on an hourly basis for the next 4 days without having your own metering equipment or system-specific generation data.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: dev@stromdao.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.default_api import DefaultApi  # noqa: E501


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_prediction(self):
        """Test case for prediction

        Retrieve PV Forecast without metering  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
