/*
 * SolarEnergyPrediction
 * The PV generation forecast for unmetered PV systems makes it possible to predict production of a PV system on an hourly basis for the next 4 days without having your own metering equipment or system-specific generation data.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev@stromdao.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DefaultApi
 */
@Disabled
public class DefaultApiTest {

    private final DefaultApi api = new DefaultApi();

    /**
     * Retrieve PV Forecast without metering
     *
     * The PV generation forecast for unmetered PV systems makes it possible to predict production of a PV system on an hourly basis for the next 4 days without having your own metering equipment or system-specific generation data.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void predictionTest() throws ApiException {
        String xRapidAPIKey = null;
        String xRapidAPIHost = null;
        Float lat = null;
        Float lon = null;
        String zip = null;
        Integer deg = null;
        Integer az = null;
        Integer wp = null;
        Integer loss = null;
        String plant = null;
        String decoration = null;
        api.prediction(xRapidAPIKey, xRapidAPIHost, lat, lon, zip, deg, az, wp, loss, plant, decoration);
        // TODO: test validations
    }

}
